### ISSUE TITLE
Please support compiling with OpenSSL 1.1

### ISSUE THREAD

**Issue by FauxFaux** [boxbackup/boxbackup#16]
OpenSSL 1.1 has been out for a while, and is becoming the default on Linux distributions.

It looks like everything works if one uses `EVP_CIPHER_CTX *ctx` as a pointer, and calls `new`/`free` instead of `init`/`cleanup`. I didn't test it extensively, beyond letting the test suite run.

The patch against Debian's old version looks like: https://gist.github.com/FauxFaux/8675680985c40d187eff2cf06e8dce70

**Comment by qris** [comment]
Thanks for the message and the patch! Do the regtests really all pass for you with this patch? I'm running into [this issue](https://www.mail-archive.com/openvpn-devel@lists.sourceforge.net/msg14118.html) which seems to require non-trivially changing the way that we call `EVP_CipherInit(_ex)` and the patch doesn't seem to do that.

**Comment by FauxFaux** [comment]
Apparently the package build runs the tests, but ignores their results. Argh, sorry.

I was unaware of the issue you linked, and was relying on test suites, which has gone terribly poorly.

https://sources.debian.net/src/boxbackup/0.11.1~r2837-4/debian/rules/#L34
