### ISSUE TITLE
Website non-functional

### ISSUE THREAD

**Issue by rthille** [boxbackup/boxbackup#25]
Visiting https://www.boxbackup.org/ I just get a bunch of errors from Trac.

**Comment by jamesog** [comment]
Thanks @rthille I'm taking a look.

Looks like something got upset after the hosting provider had a storage outage.

**Comment by jamesog** [comment]
It should be back up now. I'll take a look at why monitoring didn't alert me of this :-/

**Comment by rthille** [comment]
Thanks, working now.
