### ISSUE TITLE
build is failing according to the readme

### ISSUE THREAD

**Issue by matkoniecz** [boxbackup/boxbackup#27]
https://github.com/boxbackup/boxbackup#box-backup

**Comment by qris** [comment]
Thanks for the report! I blame SourceForge and their terrible reliability which forced me to hard-code the NSIS download URL, which has now changed. I've backed out that change in #28 and I'm running the tests, which seem to be working fine so far, with the hope that I can merge this fix very shortly. The code itself is unchanged and would build fine on any supported platform, but not on the AppVeyor CI service that we use.
