### ISSUE TITLE
consider documenting whatever code in this repo is a client, server or both

### ISSUE THREAD

**Issue by matkoniecz** [boxbackup/boxbackup#31]
> Box Backup is an open source, completely automatic, secure, encrypted on-line backup system.

Is not answering question whatever boxbackup includes enough code to run it by myself or is this code merely client connecting to a server controlled by somebody.

**Comment by jwlemke** [comment]
On 2018-08-18 03:13 , Mateusz Konieczny wrote:
> Is not answering question whatever boxbackup includes enough code to 
> run it by myself or is this code merely client connecting to a server 
> controlled by somebody.
I don't remember if there are separate server and client packages or if 
they are bundled together, but yes both sides are available.  I have run 
this for backups from a couple of machines to a home server for at least 
a year.   Great software.

-- 
The pessimist complains about the wind;
The optimist expects it to change;
The realist adjusts the sails.
William A. Ward
