### ISSUE TITLE
outdated installation instruction

### ISSUE THREAD

**Issue by matkoniecz** [boxbackup/boxbackup#32]
Readme refers to https://www.boxbackup.org/wiki/Installation  ("Please see the website for more information, including installation instructions.")

This site has

> As of may 2007 official packages are available for Box Backup in debian main: 

As this text is not tracked in repository I am unable to make a PR.

**Comment by qris** [comment]
Hi @matkoniecz, thanks for the report. I've removed the words "Since may 2007" since it's still true today. Hope this helps, but please reopen this issue if not.
